### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by rainbyrd** [Love-and-logic/urlshorty#12]
Update the README.md to inform people of your git branching model, as well as a Getting Started guide that informs people to install node modules, etc.

Establish application logic. If there is no shortened string included in the request, generate a random string of 6 characters to be the shortened URL.

**Comment by ayyrickay** [comment]
Not trying to be a control freak here - but typically, a Github issue maps to a task. So I'm going to rename these for now.

Thanks for being patient with me, I know I'm being persnickety!

**Comment by ayyrickay** [comment]
@eabg @Love-and-logic @rainbyrd Any progress on these? If you can take a second to close issues that are completed and populate new ones, it gives Sarah and I an idea of what you're doing!
