### ISSUE TITLE
Readme formatting update

### ISSUE THREAD

**Issue by rainbyrd** [Love-and-logic/urlshorty#28]
When merging the develop branch into master, the format confused me and I deleted the wrong thing. Gotta fix that!

**Comment by Love-and-logic** [comment]
@rainbyrd no worries! Been there too. There is a branch added chore/read-me-title :)

**Comment by rainbyrd** [comment]
Ok I already requested that it be merged, uploaded it into the Saturday branch since that’s what I was still working on.

**Comment by rainbyrd** [comment]
Actually, since we’re moving package lock I’ll just do one more pull request and close the Saturday pull.
