### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by eabg** [Love-and-logic/urlshorty#33]
It would be great to set up a folder structure, but how??!

├── build                   # Compiled files (alternatively `dist`)
├── docs                    # Documentation files (alternatively `doc`)
├── src                     # Source files (alternatively `lib` or `app`)
├── test                    # Automated tests (alternatively `spec` or `tests`)
├── tools                   # Tools and utilities
├── LICENSE
└── README.md

**Comment by Love-and-logic** [comment]
@rainbyrd  thank you for updating!
