### ISSUE TITLE
can you guys add me as a Collaborator to this github page?

### ISSUE THREAD

**Issue by colindodsworth** [Love-and-logic/urlshorty#6]
can you guys add me as a Collaborator to this github page?
I think thats why it wasnt letting me push stuff, & currently it only lists 3 members (you guys)

thanks
colin

**Comment by rainbyrd** [comment]
Hey! At first glance, it says you are a collaborator next to your name on that comment above, and when i hover over that it says 'this user has been invited to collaborate on the urlshorty repository'!

I will look into it further right now and see if you are listed on the home page.

**Comment by vanwars** [comment]
Colin,

I think you have to confirm it (via email). May be in your Spam?

**Comment by rainbyrd** [comment]
After looking around, I think the problem is that we're pushing to master, which is protected. I succeeded by pushing my commit to my own branch, but after pulling from my own branch lost all the files EJ had uploaded to master from my computer as well as our new folder structure. Perhaps creating the Develop branch is needed.

**Comment by colindodsworth** [comment]
hurray! I had meant Contributor, and I guess I just hadnt hit confirm til just now.
Ricky had thought that would be why it wasn't letting me push, but unfortunately it's _still_ not letting me, even though I'm successfully confirmed as a collaborator, and now pushing to a branch. gah. Ricky had also said we should push a change like this to a "refactor" branch titled: **_refactor/change-file-structure_** (instead of to a "develop" branch. I'm not entirely clear the delineation there yet, but that's what he suggested. I guess develop is more for big new features, this is more like fixing stuff?) Anyways, if somebody else wants to try to make a branch titled **_refactor/change-file-structure_**, please do.
