### ISSUE TITLE
Task Yo'self

### ISSUE THREAD

**Issue by rainbyrd** [Love-and-logic/urlshorty#7]
Morgan = Update the README.md to inform people of your git branching model, as well as a Getting Started guide that informs people to install node modules, etc.

Ehidin = Finish the Client <> Server Interaction
Return the shortened string, and find an appropriate data structure for storing it (or the provided shortened URL) in local memory. DO NOT USE A DATABASE.

Morgan = Establish application logic. If there is no shortened string included in the request, generate a random string of 6 characters to be the shortened URL.

E.j. = Begin implementing reroute logic
Write an endpoint that can receive the shortened tag and redirect to a long URL. For initial testing, you can focus on just creating any route that can redirect to a URL of your determination (e.g., a shortened URL that goes to http://google.com ) (Links to an external site.)Links to an external site.

**Comment by ayyrickay** [comment]
@rainbyrd Can you (or somebody on your team) break these into separate issues and assign them (on the right hand side of the page, you can see that there's an "assignees" feature
