### ISSUE TITLE
Having trouble uploading to github....

### ISSUE THREAD

**Issue by rainbyrd** [Love-and-logic/urlshorty#8]
$ git push
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 699 bytes | 233.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/Love-and-logic/urlshorty.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Love-and-logic/urlshorty.git'

**Comment by rainbyrd** [comment]
After looking around, I think the problem is that i'm pushing to master, which we protected. Duh!

**Comment by colindodsworth** [comment]
yeah I'm getting:
> Counting objects: 13, done.
> Delta compression using up to 8 threads.
> Compressing objects: 100% (6/6), done.
> Writing objects: 100% (6/6), 928 bytes | 0 bytes/s, done.
> Total 6 (delta 1), reused 0 (delta 0)
> remote: Resolving deltas: 100% (1/1), completed with 1 local object.
> remote: error: GH006: Protected branch update failed for refs/heads/master.
> remote: error: At least 1 approving review is required by reviewers with write access.
> To https://github.com/Love-and-logic/urlshorty.git
>  ! [remote rejected] master -> master (protected branch hook declined)
> error: failed to push some refs to 'https://github.com/Love-and-logic/urlshorty.git'

but I'm not even pushing to Master, so it might be something else wrong? I'm trying to push to a new branch I tried to create called (at Ricky's suggestion) called **_refactor/change-file-structure_**
but it's still not letting me push nor add the new branch

**Comment by colindodsworth** [comment]
and I'm officially approved as a "Contributor" now too, so it's not that either

**Comment by colindodsworth** [comment]
@ayyrickay ?

**Comment by colindodsworth** [comment]
oh I think it let me! haha!! can somebody review my **_refactor/change-file-structure_** branch, see if it's good & merge it with master?
